// <auto-generated />
namespace PersonalTrainer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedstomodelnames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedstomodelnames));
        
        string IMigrationMetadata.Id
        {
            get { return "201710041545447_Added s to model names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
