// <auto-generated />
namespace PersonalTrainer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedgoalweighttoprofilemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedgoalweighttoprofilemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201803200116544_added goal weight to profile model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
